version: "3.6"

services:
  service-1:
    container_name: python-fastapi-service
    build:
      context: ./service-1
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  service-2:
    container_name: express-js-service
    build:
      context: ./service-2
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    
  service-3:
    container_name: gorilla-mux-service
    build:
      context: ./service-3
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    
  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./429.html:/var/www/429.html
    ports:
      - 80:80
